#!/bin/bash

source ../utils/utils.sh
docker-compose down -v

CLUSTER_ID=`docker run --rm confluentinc/cp-server:7.7.1 /bin/kafka-storage random-uuid`
echo "CLUSTER_ID=$CLUSTER_ID" > .env

DIRS="kafka-1-vol/ kafka-2-vol/ kafka-3-vol/ kafka-4-vol/ kraft-1-vol/ kraft-2-vol/ kraft-3-vol/"

for i in $DIRS; do
  sudo rm -fr $i
  mkdir $i
# Make sure the user has read and write permissions.
  chown -R 1000:1000 $i
done;


docker-compose up -d

KAFKA_1_IP=$(container_to_ip kafka-1)
KAFKA_2_IP=$(container_to_ip kafka-2)
KAFKA_3_IP=$(container_to_ip kafka-3)
KAFKA_4_IP=$(container_to_ip kafka-4)
KRAFT_1_IP=$(container_to_ip kraft-1)
KRAFT_2_IP=$(container_to_ip kraft-2)
KRAFT_3_IP=$(container_to_ip kraft-3)
interface=eth0


main() {
	sleep 20
	create_topic kafka-1 test 1 4 3
	sleep 5

	get_state_kraft kraft-1 $CLUSTER_ID '1@kraft-1:29093,2@kraft-2:29093,3@kraft-3:29093'

	send_message kafka-1 'before network outage'
	read_messages kafka-1 1

	kraft_mode kraft-1 kraft-2 kraft-3
 
	log 'Making sure the controller (kraft-3) that can be seen by the other controllers after the outage is not the leader by rebooting it'
        docker-compose restart kraft-3  
        sleep 5
	kraft_mode kraft-1 kraft-2 kraft-3

	log 'Network outage starts'

	# DC-A: kafka-1, kafka-2, kraft-1 (id=1)
	# DC-B: kafka-3, kafka-4, kraft-2 (id=2)
	# DC-C: kraft-3 (id=3)

        # rack A
        block_port kraft-1 29093 $KRAFT_2_IP
        # rack B
        block_port kraft-2 29093 $KRAFT_1_IP

	log "Let's wait for the timeouts to occur"
	sleep 15
        
	log "We might see some leader instability between controller 1 and 2 and then convergence to controller 3"
	kraft_mode kraft-1 kraft-2 kraft-3
	kraft_mode kraft-1 kraft-2 kraft-3

	log 'Network outage ends'
	remove_partition kafka-1 kafka-2 kafka-3 kafka-4 kraft-1 kraft-2 kraft-3

       
	log 'Rebooting kraft-3 to give a chanche to other controllers to become leaders now that network outage is removed'
        docker-compose restart kraft-3  
        sleep 5
	log 'Waiting for the quorum to be stabilized, we should be able to get quorum info from all controllers'
	sleep 5

	kraft_mode kraft-1 kraft-2 kraft-3

	get_state_kraft kraft-1 $CLUSTER_ID '1@kraft-1:29093,2@kraft-2:29093,3@kraft-3:29093'
	get_state_kraft kraft-2 $CLUSTER_ID '1@kraft-1:29093,2@kraft-2:29093,3@kraft-3:29093'
	get_state_kraft kraft-3 $CLUSTER_ID '1@kraft-1:29093,2@kraft-2:29093,3@kraft-3:29093'

	send_message kafka-1 'after network outage'
	read_messages kafka-1 2
}

main
